\\ Auto-generated by witness measure — do not edit
\\ 2026-07-22T18:03:40.092Z

(set *measurements* [
  ["Card Title" "18px sans-serif" 77.361328125]
  ["View Details" "14px sans-serif" 76.78125]
  ["Save" "14px sans-serif" 31.91015625]
])
