#!/usr/bin/env node
// examples/card-cloth.js — build the HTML-in-canvas cloth demo
//
// Pipeline (inspired by html-in-canvas/plugins/html-cloth.mjs):
//   1. Load examples/card-cloth.shen — every assert-fits / proven-text proof
//      runs at load time; the build FAILS here if any text overflows.
//   2. SSR the proven view to absolutely-positioned HTML (render-html-doc).
//   3. Embed the fragment in examples/card-cloth.html, where the browser
//      rasterizes it into a <canvas> texture via SVG <foreignObject> and
//      drapes it over an interactive Verlet cloth.
//
// Usage: node examples/card-cloth.js   (writes examples/card-cloth.html)

const fs = require('fs');
const path = require('path');
const { boot } = require('../boot');

const SHEN_FILE = path.join(__dirname, 'card-cloth.shen');
const OUT_FILE = path.join(__dirname, 'card-cloth.html');

async function main() {
  const $ = await boot();
  await $.exec('(tc -)');
  await $.load(SHEN_FILE); // proofs run here — throws on overflow

  const doc = await $.exec('(render-html-doc (solve-layout (render-view) 360 600))');

  const bodyMatch = doc.match(/<body>\s*([\s\S]*?)\s*<\/body>/);
  if (!bodyMatch) throw new Error('render-html-doc produced no <body>');
  const fragment = bodyMatch[1];

  const rootMatch = fragment.match(/width:(\d+(?:\.\d+)?)px;height:(\d+(?:\.\d+)?)px/);
  if (!rootMatch) throw new Error('could not read root frame dimensions');
  const texW = Math.ceil(parseFloat(rootMatch[1]));
  const texH = Math.ceil(parseFloat(rootMatch[2]));

  const proven = (fragment.match(/data-witness-overflow="visible"/g) || []).length;
  const handled = (fragment.match(/data-witness-overflow="(ellipsis|clip)"/g) || []).length;

  const html = template({
    fragment: JSON.stringify(fragment),
    texW,
    texH,
    proven,
    handled,
  });

  fs.writeFileSync(OUT_FILE, html);
  console.log(
    `Wrote ${path.relative(process.cwd(), OUT_FILE)} ` +
    `(texture ${texW}x${texH}, ${proven} proven cells, ${handled} handled cells)`
  );
}

function template({ fragment, texW, texH, proven, handled }) {
  return `<!DOCTYPE html>
<!-- Generated by examples/card-cloth.js — do not edit by hand.
     The texture markup below was proven overflow-free by witness at build time. -->
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>witness — proven cloth</title>
<style>
  :root { color-scheme: dark; }
  * { margin: 0; box-sizing: border-box; }
  body {
    min-height: 100vh; display: flex; flex-direction: column; align-items: center;
    background: radial-gradient(1200px 700px at 50% -10%, #1e293b 0%, #0b1120 60%, #060913 100%);
    color: #cbd5e1; font-family: system-ui, sans-serif; overflow: hidden;
  }
  header { text-align: center; padding: 22px 16px 4px; }
  header h1 { color: #f1f5f9; font-size: 20px; font-weight: 650; letter-spacing: 0.2px; }
  header p { font-size: 13px; color: #7c8aa5; margin-top: 4px; }
  header code { color: #93c5fd; font-family: ui-monospace, monospace; font-size: 12px; }
  #stage { flex: 1; width: 100%; touch-action: none; cursor: grab; }
  #stage.grabbing { cursor: grabbing; }
  footer {
    display: flex; gap: 18px; align-items: center; flex-wrap: wrap; justify-content: center;
    padding: 10px 16px 18px; font-size: 12px; color: #7c8aa5;
  }
  footer label { display: flex; align-items: center; gap: 7px; }
  footer input[type=range] { width: 110px; accent-color: #60a5fa; }
  footer button {
    background: #172136; color: #bfdbfe; border: 1px solid #2b3b5c; border-radius: 8px;
    padding: 5px 12px; font-size: 12px; cursor: pointer;
  }
  footer button:hover { background: #1d2b47; }
  .proof { color: #4ade80; }
</style>
</head>
<body>
<header>
  <h1>Proven cloth</h1>
  <p>Witness-proven HTML, rasterized into a canvas texture and draped on a Verlet cloth
     &mdash; drag it, or turn up the wind.
     <span class="proof">${proven} proven-text cells &check;</span>
     <span class="proof">${handled} handled-text cell${handled === 1 ? '' : 's'} &check;</span></p>
  <p>Texture source: <code>examples/card-cloth.shen</code> via
     <code>render-html-doc (solve-layout (render-view) ...)</code></p>
</header>
<canvas id="stage"></canvas>
<footer>
  <label>Wind <input id="wind" type="range" min="0" max="100" value="28"></label>
  <label>Gravity <input id="gravity" type="range" min="0" max="100" value="40"></label>
  <button id="gust">Gust</button>
  <button id="wire">Wireframe</button>
</footer>
<script>
'use strict';

// --- The proven texture markup, injected at build time -----------------------
const FRAGMENT = ${fragment};
const TEX_W = ${texW}, TEX_H = ${texH};

// --- Rasterize HTML -> canvas texture via SVG foreignObject ------------------
// Same trick as html-cloth.mjs: the DOM does the typesetting, the canvas gets
// the pixels. Colors are attached with CSS attribute selectors keyed off the
// spans' inline font-size, so witness's SSR output stays purely structural.
const TEX_SCALE = 2;
const texture = document.createElement('canvas');
texture.width = TEX_W * TEX_SCALE;
texture.height = TEX_H * TEX_SCALE;
let textureReady = false;

function buildTexture() {
  const style =
    '<style>' +
    'span[data-witness-text]{color:#1e293b;}' +
    'span[style*="font-size:24px"]{color:#0f172a;font-weight:700;}' +
    'span[style*="font-size:14px"]{color:#2563eb;font-weight:600;}' +
    'span[style*="font-size:13px"]{color:#64748b;}' +
    // NOTE: color only for snug boxes — changing font-family or weight here
    // would change text metrics and silently invalidate the proven widths.
    'span[style*="font-size:12px"]{color:#166534;white-space:nowrap;}' +
    '</style>';
  const wrapper =
    '<div xmlns="http://www.w3.org/1999/xhtml" style="position:relative;' +
    'width:' + TEX_W + 'px;height:' + TEX_H + 'px;' +
    'background:linear-gradient(160deg,#f8fafc 0%,#e2e8f0 55%,#cbd5e1 100%);' +
    'border:1px solid #94a3b8;border-radius:10px;overflow:hidden;">' +
    '<div style="position:absolute;left:0;top:0;right:0;height:6px;' +
    'background:linear-gradient(90deg,#2563eb,#7c3aed,#16a34a);"></div>' +
    style + FRAGMENT + '</div>';
  const svg =
    '<svg xmlns="http://www.w3.org/2000/svg" width="' + TEX_W + '" height="' + TEX_H + '">' +
    '<foreignObject width="100%" height="100%">' + wrapper + '</foreignObject></svg>';

  const img = new Image();
  img.onload = () => {
    const tctx = texture.getContext('2d');
    tctx.drawImage(img, 0, 0, texture.width, texture.height);
    textureReady = true;
  };
  img.onerror = () => console.error('cloth: texture rasterization failed');
  img.src = 'data:image/svg+xml;charset=utf-8,' + encodeURIComponent(svg);
}
buildTexture();

// --- Verlet cloth ------------------------------------------------------------
const COLS = 26;
const ROWS = Math.max(8, Math.round(COLS * (TEX_H / TEX_W)));
const ITERATIONS = 4;
const DAMPING = 0.985;

const canvas = document.getElementById('stage');
const ctx = canvas.getContext('2d');
const windInput = document.getElementById('wind');
const gravityInput = document.getElementById('gravity');
let wireframe = false;

let points = [];       // {x,y,px,py,pinned}
let constraints = [];  // {a,b,rest}
let spacing = 12;
let clothW = 0, clothH = 0, originX = 0, originY = 0;

function buildCloth() {
  const rect = canvas.getBoundingClientRect();
  clothW = Math.min(rect.width * 0.72, 560);
  clothH = clothW * (TEX_H / TEX_W);
  spacing = clothW / COLS;
  originX = (rect.width - clothW) / 2;
  originY = Math.min(40, rect.height * 0.06);

  points = [];
  constraints = [];
  for (let y = 0; y <= ROWS; y++) {
    for (let x = 0; x <= COLS; x++) {
      const px = originX + (x / COLS) * clothW;
      const py = originY + (y / ROWS) * clothH;
      points.push({ x: px, y: py, px, py, pinned: y === 0 });
    }
  }
  const idx = (x, y) => y * (COLS + 1) + x;
  for (let y = 0; y <= ROWS; y++) {
    for (let x = 0; x <= COLS; x++) {
      if (x < COLS) constraints.push({ a: idx(x, y), b: idx(x + 1, y), rest: clothW / COLS });
      if (y < ROWS) constraints.push({ a: idx(x, y), b: idx(x, y + 1), rest: clothH / ROWS });
    }
  }
}

let gustUntil = 0;
let time = 0;

function step(dt) {
  time += dt;
  const wind = (windInput.value / 100) * 26 + (performance.now() < gustUntil ? 90 : 0);
  const gravity = (gravityInput.value / 100) * 55;

  for (const p of points) {
    if (p.pinned) continue;
    const vx = (p.x - p.px) * DAMPING;
    const vy = (p.y - p.py) * DAMPING;
    p.px = p.x; p.py = p.y;
    const row = (p.y - originY) / Math.max(1, clothH);
    const gustX = Math.sin(time * 1.9 + row * 5.0) * wind + Math.sin(time * 0.7) * wind * 0.4;
    const gustY = Math.cos(time * 1.3 + row * 3.0) * wind * 0.12;
    p.x += vx + gustX * dt * dt * 60;
    p.y += vy + (gravity + gustY) * dt * dt * 60;
  }

  for (let i = 0; i < ITERATIONS; i++) {
    for (const c of constraints) {
      const a = points[c.a], b = points[c.b];
      let dx = b.x - a.x, dy = b.y - a.y;
      const dist = Math.hypot(dx, dy) || 0.0001;
      const diff = (dist - c.rest) / dist;
      const ax = dx * 0.5 * diff, ay = dy * 0.5 * diff;
      if (!a.pinned) { a.x += ax; a.y += ay; }
      if (!b.pinned) { b.x -= ax; b.y -= ay; }
    }
    if (dragging && grabbed !== null) {
      points[grabbed].x = pointer.x;
      points[grabbed].y = pointer.y;
    }
  }
}

// --- Pointer interaction -----------------------------------------------------
const pointer = { x: 0, y: 0, lx: 0, ly: 0 };
let dragging = false;
let grabbed = null;

function canvasPos(e) {
  const r = canvas.getBoundingClientRect();
  return { x: e.clientX - r.left, y: e.clientY - r.top };
}

canvas.addEventListener('pointerdown', e => {
  const { x, y } = canvasPos(e);
  pointer.x = x; pointer.y = y;
  let best = null, bestD = 45;
  points.forEach((p, i) => {
    if (p.pinned) return;
    const d = Math.hypot(p.x - x, p.y - y);
    if (d < bestD) { bestD = d; best = i; }
  });
  grabbed = best;
  dragging = true;
  canvas.classList.add('grabbing');
  canvas.setPointerCapture(e.pointerId);
});
canvas.addEventListener('pointermove', e => {
  const { x, y } = canvasPos(e);
  pointer.lx = pointer.x; pointer.ly = pointer.y;
  pointer.x = x; pointer.y = y;
  if (!dragging) {
    // brush past the cloth: nudge nearby points
    const mvx = pointer.x - pointer.lx, mvy = pointer.y - pointer.ly;
    for (const p of points) {
      if (p.pinned) continue;
      const d = Math.hypot(p.x - x, p.y - y);
      if (d < 30) { p.x += mvx * 0.35; p.y += mvy * 0.35; }
    }
  }
});
window.addEventListener('pointerup', () => {
  dragging = false; grabbed = null;
  canvas.classList.remove('grabbing');
});
document.getElementById('gust').addEventListener('click', () => {
  gustUntil = performance.now() + 450;
});
document.getElementById('wire').addEventListener('click', () => {
  wireframe = !wireframe;
});

// --- Textured rendering ------------------------------------------------------
// Each cloth quad maps a texture quad; each is drawn as two affine-mapped
// triangles (the classic 2D-canvas texture mapping trick).
function drawTexturedTriangle(x0, y0, x1, y1, x2, y2, u0, v0, u1, v1, u2, v2) {
  ctx.save();
  ctx.beginPath();
  // scale the clip region slightly out from the centroid to hide seams
  const cx = (x0 + x1 + x2) / 3, cy = (y0 + y1 + y2) / 3;
  const s = 1.04;
  ctx.moveTo(cx + (x0 - cx) * s, cy + (y0 - cy) * s);
  ctx.lineTo(cx + (x1 - cx) * s, cy + (y1 - cy) * s);
  ctx.lineTo(cx + (x2 - cx) * s, cy + (y2 - cy) * s);
  ctx.closePath();
  ctx.clip();

  // Cramer's rule for the affine map (u,v) -> (x,y)
  const delta = u0 * v1 + v0 * u2 + u1 * v2 - v1 * u2 - v0 * u1 - u0 * v2;
  if (Math.abs(delta) < 1e-9) { ctx.restore(); return; }
  const dInv = 1 / delta;
  const a = (x0 * (v1 - v2) + x1 * (v2 - v0) + x2 * (v0 - v1)) * dInv;
  const b = (y0 * (v1 - v2) + y1 * (v2 - v0) + y2 * (v0 - v1)) * dInv;
  const c = (x0 * (u2 - u1) + x1 * (u0 - u2) + x2 * (u1 - u0)) * dInv;
  const d = (y0 * (u2 - u1) + y1 * (u0 - u2) + y2 * (u1 - u0)) * dInv;
  const e = x0 - a * u0 - c * v0;
  const f = y0 - b * u0 - d * v0;
  ctx.transform(a, b, c, d, e, f);
  ctx.drawImage(texture, 0, 0);
  ctx.restore();
}

function render() {
  const dpr = window.devicePixelRatio || 1;
  ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
  ctx.clearRect(0, 0, canvas.width / dpr, canvas.height / dpr);

  const idx = (x, y) => y * (COLS + 1) + x;
  const su = texture.width / COLS, sv = texture.height / ROWS;

  if (textureReady && !wireframe) {
    for (let y = 0; y < ROWS; y++) {
      for (let x = 0; x < COLS; x++) {
        const p00 = points[idx(x, y)], p10 = points[idx(x + 1, y)];
        const p01 = points[idx(x, y + 1)], p11 = points[idx(x + 1, y + 1)];
        const u = x * su, v = y * sv;
        drawTexturedTriangle(p00.x, p00.y, p10.x, p10.y, p11.x, p11.y,
                             u, v, u + su, v, u + su, v + sv);
        drawTexturedTriangle(p00.x, p00.y, p11.x, p11.y, p01.x, p01.y,
                             u, v, u + su, v + sv, u, v + sv);
      }
    }
  } else {
    ctx.strokeStyle = textureReady ? 'rgba(148,163,184,0.75)' : 'rgba(148,163,184,0.3)';
    ctx.lineWidth = 1;
    ctx.beginPath();
    for (const c of constraints) {
      ctx.moveTo(points[c.a].x, points[c.a].y);
      ctx.lineTo(points[c.b].x, points[c.b].y);
    }
    ctx.stroke();
  }

  // pins
  ctx.fillStyle = '#64748b';
  for (let x = 0; x <= COLS; x += 2) {
    const p = points[idx(x, 0)];
    ctx.beginPath();
    ctx.arc(p.x, p.y, 2.2, 0, Math.PI * 2);
    ctx.fill();
  }
}

// --- Main loop ---------------------------------------------------------------
function resize() {
  const rect = canvas.getBoundingClientRect();
  const dpr = window.devicePixelRatio || 1;
  canvas.width = Math.max(1, Math.round(rect.width * dpr));
  canvas.height = Math.max(1, Math.round(rect.height * dpr));
  buildCloth();
}
window.addEventListener('resize', resize);
resize();

let last = performance.now();
function frame(now) {
  const dt = Math.min(0.033, (now - last) / 1000);
  last = now;
  step(dt);
  render();
  requestAnimationFrame(frame);
}
requestAnimationFrame(frame);
</script>
</body>
</html>
`;
}

main().catch(err => { console.error(err.message || err); process.exit(1); });
